server.port: 7070
spring.profiles.active: dev
---

spring.profiles: dev
server.port: 8080
spring.h2.console.enabled: true


---

spring.profiles: prod
server.port: 8888

# MySQL config described here:
# https://springframework.guru/configuring-spring-boot-for-mysql
spring.h2.console.enabled: true

#spring.datasource.url: jdbc:mysql://localhost:3306/springbootdb
#spring.datasource.username: root
#spring.datasource.password:

# NOTE: If this was actually a production database, you not tell Hibernate
# to use the create-drop option. This tells Hibernate to recreate the database on startup.
# Definitely not the behavior we want.
# You can set this property to the following values:
# none, validate, update, create-drop.
# If this was actually a production database, you probably would want to use validate.
spring.jpa.hibernate.ddl-auto: create-drop
